name:                lCirc
version:             0.1.0.0
github:              "faezs/lCirc"
license:             BSD3
author:              "Faez Shakil"
maintainer:          "faez.shakil@gmail.com"
copyright:           "2019 Faez Shakil"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/faezs/lCirc#readme>

dependencies:
- base >= 4.7 && < 5
- concat-classes
- concat-examples
- concat-plugin
- QuickCheck
- hspec
- checkers
- text
- finite-typelits
- containers
- vector-sized
- newtype-generics
- algebraic-graphs
library:
  source-dirs: src

executables:
  lCirc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lCirc

tests:
  lCirc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lCirc
    - QuickCheck
    - hspec
    - checkers
